adding temp code to test (#4)
* adding temp code to test

* fixed few bugs

* refactored the scripts as per new plugins policy.

diff --git a/kmux/kmux b/kmux/kmux
--- a/kmux/kmux
+++ b/kmux/kmux
@@ -1,7 +1,7 @@
 #!/bin/bash
 # AUTHOR: Abhishek Tamrakar
 # EMAIL: abhishek.tamrakar08@gmail.com
-# VERSION: 0.0.1
+# VERSION: 1.1.0
 # LICENSE: Copyright (C) 2018 Abhishek Tamrakar
 #
 #  Licensed under the Apache License, Version 2.0 (the "License");
@@ -17,13 +17,28 @@
 #   limitations under the License.
 ##
 #define variables
-KUBE=${KUBECTL_PLUGINS_CALLER}
+KUBECTL=$(which kubectl)
 GET=$(which egrep)
 AWK=$(which awk)
 TMUX=$(which tmux)
 SCRIPT=${0##*/}
 NEWSESSION="${SCRIPT%%.*}$RANDOM"
 # define functions
+usage()
+{
+  cat <<_EOF_
+    $SCRIPT <options>
+
+    options:
+        -n|--namespace:  KUBECTLrnetes NAMESPACE or export NAMESPACE=<value>
+        -s|--session:    Session Name for TMUX
+        -e|--show-error: Show only errored pods
+        -h|--help:       Print this help and quit
+_EOF_
+
+exit 1
+}
+
 info()
 {
   printf '\n%s: %s\n' "INFO" "$@"
@@ -42,11 +57,11 @@ fatal()
 
 check_commands()
 {
-  CMDS=(GET AWK TMUX KUBE)
-  for cmd in ${CMDS[@]}
+  CMDS=(TMUX KUBECTL)
+  for CMD in ${CMDS[@]}
   do
-     if [ x${!cmd} = x ]; then
-       fatal "${!cmd} not found"
+     if [ x${!CMD} = x ]; then
+       fatal "${CMD,,} not found"
      fi
   done
 }
@@ -67,9 +82,9 @@ check_session()
 {
   if $TMUX has-session -t $THIS_SESSION 2>/dev/null;
   then
-    is_session=0
+    IS_SESSION=0
   else
-    is_session=1
+    IS_SESSION=1
   fi
 }
 
@@ -83,7 +98,7 @@ create_session()
 start_split()
 {
   check_session
-  if [ $is_session -eq 1 ]; then
+  if [ $IS_SESSION -eq 1 ]; then
     # create session
     start_server
     create_session
@@ -93,12 +108,12 @@ start_split()
     select-layout tiled \;
 }
 
-run_kube_command()
+run_KUBECTL_command()
 {
   # only for use with plugin.
-  NAMESPACE=${KUBECTL_PLUGINS_LOCAL_FLAG_NAMESPACE:-$KUBECTL_PLUGINS_CURRENT_NAMESPACE}
-  THIS_SESSION=${KUBECTL_PLUGINS_LOCAL_FLAG_SESSION:-$NEWSESSION}
-  SHOWERROR="${KUBECTL_PLUGINS_LOCAL_FLAG_ERROR}"
+  local THIS_NAMESPACE=${1}
+  local THIS_SESSION=${2}
+  local SHOWERROR="${3}"
   n=0
   while IFS=' ' read -r POD CONTAINERS
   do
@@ -110,19 +125,19 @@ run_kube_command()
         warn "Looks like there is a problem getting pods data."
         break
       fi
-      if [ ${SHOWERROR} -eq 1 ]; then
+      if [ ${SHOWERROR:-0} -eq 1 ]; then
         # if enabled
-        COMMAND="$KUBE logs -f $POD -c $CONTAINER -n $NAMESPACE | $GET '[Ee]rror|ERROR|[Ww]arn|WARN|[Ee]xception'"
+        COMMAND="$KUBECTL logs -f $POD -c $CONTAINER -n $NAMESPACE | $GET '[Ee]rror|[E]RROR|[Ww]arn|[W]ARN|[Ee]xception'"
       else
         #normal run
-        COMMAND="$KUBE logs -f $POD -c $CONTAINER -n $NAMESPACE"
+        COMMAND="$KUBECTL logs -f $POD -c $CONTAINER -n $NAMESPACE"
       fi
 
       start_split
     done
     $TMUX renamew $POD 2>/dev/null
     ((n+=1))
-  done< <($KUBE get pods -n $NAMESPACE \
+  done< <($KUBECTL get pods -n $NAMESPACE \
 	--ignore-not-found=true \
 	-o=custom-columns=NAME:.metadata.name,CONTAINERS:.spec.containers[*].name| \
 	sed '1d')
@@ -138,6 +153,35 @@ attach_sessions()
 trap destroy 2 3 15 EXIT
 #
 # run
+while [ $# -gt 0 ]; do
+  case $1 in
+  -n|--namespace) shift; NAMESPACE=$1;;
+  -s|--session) shift; SESSION_NAME=$1;;
+  -e|--show-error) SHOWERROR=1;;
+  -h|--help) usage;;
+  *) fatal "invalid option $1";;
+  esac
+  shift;
+done
+
+# check cli availability
 check_commands
-run_kube_command
+
+# check k8s version compatibility
+COMPATIBLE_KUBECTL_VERSION=$($KUBECTL version --client --short| \
+  awk -F': ' '{ \
+    gsub("v","",$2); \
+    split($2,a,"."); \
+    if (a[1] == 1 && a[2] < 12) print "no"; else print "yes" \
+  }' \
+)
+
+if [[ "$COMPATIBLE_KUBECTL_VERSION" = "no" ]]; then
+  fatal "kubectl version is incompatible, please correct and try again."
+fi
+
+# run kubectl cli to get details
+run_KUBECTL_command $NAMESPACE $SESSION_NAME $SHOWERROR
+
+# at last attach the parent session
 attach_sessions
